"""Vendor Docker helpers for Pitch."""

from __future__ import annotations

import os
import http.client
import shutil
import socket
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

from pitch.common import coerce_env_path, resolved_docker_command
from pitch.routes import discovered_prti_install_root
from pitch.settings import read_env_value, read_settings_value, set_settings_value, vendor_crc_settings_path
from pitch_bootstrap import ROOT, resolve_artifact_root, resolve_asset_root, resolve_installer_drop_root, resolve_user_data_root


ASSET_ROOT = resolve_asset_root(ROOT)
USER_DATA_ROOT = resolve_user_data_root()
ARTIFACT_ROOT = resolve_artifact_root(ROOT)
INSTALLER_DROP_ROOT = resolve_installer_drop_root()
PREFLIGHT_ARTIFACT_ROOT = ARTIFACT_ROOT / "preflight"
VENDOR_DOCKER_ENV_FILENAME = "pitch-vendor-compose.env"
VENDOR_DOCKER_ENV_PATH = ARTIFACT_ROOT / "docker" / VENDOR_DOCKER_ENV_FILENAME
VENDOR_DOCKER_SETTINGS_ROOT = ARTIFACT_ROOT / "docker" / "vendor-settings"
VENDOR_DOCKER_BUILD_ROOT = ARTIFACT_ROOT / "docker" / "vendor-build"
VENDOR_DOCKER_COMPOSE_PATH = ROOT / "docker" / "pitch-vendor-compose.yml"
VENDOR_WEBVIEW_INSTALLER_DIRNAME = "webviewinstaller64"
VENDOR_WEBVIEW_INSTALLER_SOURCE_ENV = "PITCH_WEBVIEW_INSTALLER_SOURCE"
VENDOR_WEBVIEW_INSTALLER_FILENAMES = ("webview.war",)
VENDOR_WEBVIEW_INSTALLER_PATTERNS = ("pitchwebview_v*_linux64.sh",)


def container_path(*parts: str) -> str:
    return "/" + "/".join(part.strip("/\\") for part in parts if part)


def vendor_docker_env_path() -> Path:
    override = os.environ.get("PITCH_VENDOR_DOCKER_ENV_FILE", "").strip()
    if override:
        return coerce_env_path(override)
    return VENDOR_DOCKER_ENV_PATH


def vendor_docker_settings_root() -> Path:
    override = os.environ.get("PITCH_VENDOR_DOCKER_SETTINGS_ROOT", "").strip()
    if override:
        return coerce_env_path(override)
    return VENDOR_DOCKER_SETTINGS_ROOT


def vendor_docker_build_root() -> Path:
    override = os.environ.get("PITCH_VENDOR_DOCKER_BUILD_ROOT", "").strip()
    if override:
        return coerce_env_path(override)
    return VENDOR_DOCKER_BUILD_ROOT


def vendor_docker_install_root() -> Path | None:
    override = os.environ.get("PITCH_PRTI_HOME", "").strip()
    if override:
        candidate = coerce_env_path(override)
        return candidate if candidate.exists() else None
    return discovered_prti_install_root()


def write_docker_env_file(path: Path, payload: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by pitch docker init", "# Safe to edit locally; not tracked by git."]
    for key, value in payload.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def copy_vendor_settings(src_root: Path, dest_root: Path) -> None:
    dest_root.mkdir(parents=True, exist_ok=True)
    for filename in ("prti1516eCRC.settings", "prti1516eLRC.settings"):
        source = src_root / "samples" / "docker" / filename
        if source.exists():
            shutil.copy2(source, dest_root / filename)


def copy_vendor_docker_context(src_root: Path, dest_root: Path) -> None:
    dest_root.mkdir(parents=True, exist_ok=True)
    for relative_path in ("lib", "samples/docker", "versioninfo.txt"):
        source = src_root / relative_path
        destination = dest_root / relative_path
        if source.is_dir():
            shutil.copytree(source, destination, dirs_exist_ok=True)
        elif source.is_file():
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
    _copy_vendor_webview_payload(dest_root)
    _patch_vendor_docker_context(dest_root)


def _vendor_webview_source_roots() -> list[Path]:
    override = os.environ.get(VENDOR_WEBVIEW_INSTALLER_SOURCE_ENV, "").strip()
    installer_drop_root = resolve_installer_drop_root()
    roots: list[Path] = []
    if override:
        roots.append(coerce_env_path(override))
    roots.extend(
        [
            installer_drop_root / VENDOR_WEBVIEW_INSTALLER_DIRNAME,
            installer_drop_root / "webview",
            installer_drop_root,
        ]
    )
    deduped: list[Path] = []
    seen: set[str] = set()
    for root in roots:
        key = str(root)
        if key not in seen:
            deduped.append(root)
            seen.add(key)
    return deduped


def _vendor_webview_payload_candidates(source_root: Path) -> list[Path]:
    if not source_root.exists():
        return []
    if source_root.is_file():
        name = source_root.name.lower()
        if name in {filename.lower() for filename in VENDOR_WEBVIEW_INSTALLER_FILENAMES}:
            return [source_root]
        if name.startswith("pitchwebview_v") and name.endswith("_linux64.sh"):
            return [source_root]
        return []

    candidates: list[Path] = []
    for filename in VENDOR_WEBVIEW_INSTALLER_FILENAMES:
        candidates.extend(path for path in source_root.rglob(filename) if path.is_file())
    for pattern in VENDOR_WEBVIEW_INSTALLER_PATTERNS:
        candidates.extend(path for path in source_root.rglob(pattern) if path.is_file())
    deduped: list[Path] = []
    seen: set[str] = set()
    for candidate in candidates:
        key = str(candidate.resolve()) if candidate.exists() else str(candidate)
        if key not in seen:
            deduped.append(candidate)
            seen.add(key)
    return deduped


def _copy_vendor_webview_payload(dest_root: Path) -> bool:
    payload_root = dest_root / VENDOR_WEBVIEW_INSTALLER_DIRNAME
    payload_root.mkdir(parents=True, exist_ok=True)
    staged = False
    seen_names: set[str] = set()
    for source_root in _vendor_webview_source_roots():
        for candidate in _vendor_webview_payload_candidates(source_root):
            destination = payload_root / candidate.name
            if destination.name in seen_names:
                continue
            shutil.copy2(candidate, destination)
            seen_names.add(destination.name)
            staged = True
    return staged


def vendor_docker_webview_payload_available(*, build_root: Path | None = None) -> bool:
    root = build_root if build_root is not None else vendor_docker_build_root()
    payload_root = root / VENDOR_WEBVIEW_INSTALLER_DIRNAME
    if not payload_root.exists() or not payload_root.is_dir():
        return False
    return any(_vendor_webview_payload_candidates(payload_root))


def _patch_vendor_docker_context(dest_root: Path) -> None:
    dockerfile = dest_root / "samples" / "docker" / "Dockerfile"

    if dockerfile.exists():
        dockerfile.write_text(
            """#
# Pitch pRTI CRC Image Sample
#

#
# Build from Pitch pRTI installation dir.
# Build with `docker build -t prti_crc -f ./samples/docker/Dockerfile .`
#
# This pRTI CRC image uses tcp port 8989 for communication.
# Run with `docker run -p 8989:8989 -p 8080:8080 prti_crc`
#

FROM eclipse-temurin:17-jre

RUN apt-get update \\
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libxi6 libxtst6 xvfb xauth \\
    && rm -rf /var/lib/apt/lists/*

LABEL org.opencontainers.image.title="Pitch pRTI CRC Image Sample"  \\
      org.opencontainers.image.vendor="Pitch Technologies"          \\
      org.opencontainers.image.licenses="Pitch Technologies End User License Agreement"

COPY --from=tomcat:9 /usr/local/tomcat  /usr/local/tomcat
COPY webviewinstaller64/  /root/webview_installer/
COPY --chmod=755 samples/docker/install-webview.sh  /root/webview_installer/
RUN /root/webview_installer/install-webview.sh
RUN rm -rf /root/webview_installer/

COPY lib/prtifull.jar          /opt/prti1516e/lib/
COPY lib/booster1516.jar       /opt/prti1516e/lib/
COPY lib/webgui2-protocol.jar  /opt/prti1516e/lib/
COPY versioninfo.txt           /opt/prti1516e/

COPY samples/docker/prti1516eCRC.settings  /root/prti1516e/

COPY --chmod=755 samples/docker/docker-entrypoint.sh  /opt/prti1516e/

WORKDIR /opt/prti1516e

CMD ["xvfb-run", "-a", "./docker-entrypoint.sh"]

# CRC port
EXPOSE 8989/tcp

# Web View port
EXPOSE 8080/tcp
""",
            encoding="utf-8",
        )


def vendor_docker_payload(*, enable_hla4_preview: bool = False) -> dict[str, str]:
    install_root = vendor_docker_install_root()
    if install_root is None:
        raise ValueError("Could not find a pRTI installation root. Set PITCH_PRTI_HOME or install pRTI first.")

    payload = {
        "PITCH_PRTI_HOME": str(install_root),
        "PITCH_VENDOR_DOCKER_BUILD_ROOT": str(vendor_docker_build_root()),
        "PITCH_VENDOR_DOCKER_SETTINGS_ROOT": str(vendor_docker_settings_root()),
        "PITCH_VENDOR_DOCKER_ENV_FILE": str(vendor_docker_env_path()),
        "PITCH_VENDOR_CONTAINER_WORKDIR": container_path("opt", "prti1516e"),
        "PITCH_VENDOR_CONTAINER_SETTINGS_ROOT": container_path("root", "prti1516e"),
        "LICENSE_SERVER": os.environ.get("LICENSE_SERVER", "pfls"),
        "FEDERATE_COUNT": os.environ.get("FEDERATE_COUNT", "5"),
        "DISABLE_WEB_VIEW": os.environ.get("DISABLE_WEB_VIEW", ""),
        "JAVA_OPTS": os.environ.get("JAVA_OPTS", "-XX:+UseParallelGC -XX:MaxRAMPercentage=75"),
    }
    if enable_hla4_preview:
        payload["CRC_ENABLE_HLA4_PREVIEW"] = "1"
    return payload


def vendor_docker_compose_command(action: str) -> list[str]:
    env_file = vendor_docker_env_path()
    if not env_file.exists():
        raise FileNotFoundError(f"Vendor Docker env file not found: {env_file}. Run `pitch docker init` first.")
    docker_command = resolved_docker_command()
    if docker_command is None:
        raise FileNotFoundError("Could not find the Docker CLI. Install Docker Desktop or Docker Engine first.")
    command = [
        docker_command,
        "compose",
        "--env-file",
        str(env_file),
        "-f",
        str(VENDOR_DOCKER_COMPOSE_PATH),
    ]
    command.extend(action.split())
    return command


def run_vendor_docker_compose(action: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(vendor_docker_compose_command(action), check=False)


def vendor_docker_wait_for_port(host: str, port: int, *, timeout_seconds: float = 60.0, interval_seconds: float = 1.0) -> bool:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=2.0):
                return True
        except OSError:
            time.sleep(interval_seconds)
    return False


def vendor_docker_webview_check(*, timeout_seconds: float = 10.0) -> tuple[bool, str]:
    env_file = vendor_docker_env_path()
    disabled = read_env_value(env_file, "DISABLE_WEB_VIEW")
    if disabled:
        return True, "Vendor Web View probe skipped (DISABLE_WEB_VIEW is set)."
    if not env_file.exists():
        return False, f"Vendor Docker env file not found: {env_file}. Run `pitch docker init` first."
    if not vendor_docker_webview_payload_available():
        return True, "Vendor Web View probe skipped; no Web View payload was staged."

    url = "http://127.0.0.1:8080/webview/"
    request = urllib.request.Request(url, method="GET")
    deadline = time.monotonic() + timeout_seconds
    last_error: str | None = None
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
                response.read(1)
        except urllib.error.HTTPError as exc:
            return True, f"Vendor Web View responded at {url} (HTTP {exc.code})."
        except (urllib.error.URLError, http.client.RemoteDisconnected, TimeoutError, ConnectionResetError) as exc:
            last_error = str(exc)
            time.sleep(0.5)
            continue
        return True, f"Vendor Web View is reachable at {url}."
    if last_error:
        return False, f"Vendor Web View did not respond at {url}: {last_error}"
    return False, f"Vendor Web View did not respond at {url}."


def vendor_docker_smoke_check(*, timeout_seconds: float = 60.0, interval_seconds: float = 1.0) -> tuple[bool, str]:
    if not vendor_docker_wait_for_port("127.0.0.1", 8989, timeout_seconds=timeout_seconds, interval_seconds=interval_seconds):
        return False, "Vendor CRC did not become reachable on 127.0.0.1:8989 within the timeout."

    messages = ["Vendor CRC is reachable on 127.0.0.1:8989."]
    webview_ok, webview_detail = vendor_docker_webview_check(timeout_seconds=10.0)
    messages.append(webview_detail)
    if not webview_ok:
        return False, "\n".join(messages)
    return True, "\n".join(messages)


def vendor_docker_status_lines() -> list[str]:
    lines = [
        "Vendor Docker setup:",
        f"  pRTI home: {vendor_docker_install_root() or 'missing'}",
        f"  env file: {vendor_docker_env_path()}",
        f"  vendor settings overlay: {vendor_docker_settings_root()}",
        f"  vendor build context: {vendor_docker_build_root()}",
        f"  compose file: {VENDOR_DOCKER_COMPOSE_PATH}",
        f"  Web View payload staged: {'yes' if vendor_docker_webview_payload_available() else 'no'}",
    ]
    initialized = vendor_docker_env_path().exists() and vendor_docker_settings_root().exists()
    lines.append(f"  initialized: {'yes' if initialized else 'no'}")
    crc_settings_path = vendor_crc_settings_path(vendor_docker_settings_root())
    if crc_settings_path.exists():
        preview = read_settings_value(crc_settings_path, "CRC.enableHla4PreviewFeatures")
        if preview is not None:
            lines.append(f"  HLA 4 Preview: {preview}")
    return lines
